/**
 * DDLS converter — CDS Data Definition Language Sources (view entities).
 *
 * Converts between gCTS format (DDDDLSRC with embedded SOURCE) and
 * abapGit format (minimal XML metadata + separate .asddls source file).
 *
 * Key: The CDS source in DDDDLSRC.SOURCE contains a trailing
 * runtime metadata block that must be stripped:
 *   /*+[internal] {"BASEINFO": {...}}* /
 */

import type { AbapgitObject, GctsObjectData, ValidationResult } from '../core/types.js';
import type { IObjectConverter } from './base-converter.js';
import { getFirstRow, getRows } from '../formats/gcts/reader.js';
import { buildAbapGitXml } from '../formats/abapgit/xml.js';
import { buildSourceFilename } from '../formats/abapgit/naming.js';

export class DdlsConverter implements IObjectConverter {
  readonly objectType = 'DDLS';
  readonly description = 'CDS Data Definition Language Sources';
  readonly serializerClass = 'LCL_OBJECT_DDLS';

  toAbapGit(gctsObject: GctsObjectData): AbapgitObject {
    const ddddlsrc = getFirstRow(gctsObject, 'DDDDLSRC');
    const ddddlsrct = getRows(gctsObject, 'DDDDLSRCT');

    // Extract description text
    const textRow = ddddlsrct.find(r => r.DDLANGUAGE === 'E');
    const description = (textRow?.DDTEXT ?? '') as string;

    // Extract source type
    const sourceType = (ddddlsrc?.SOURCE_TYPE ?? '') as string;

    // Build minimal XML metadata
    const values: Record<string, unknown> = {
      DDLS: {
        DDLNAME: gctsObject.objectName,
        DDLANGUAGE: 'E',
        DDTEXT: description,
        ...(sourceType ? { SOURCE_TYPE: sourceType } : {}),
      },
    };

    const xmlContent = buildAbapGitXml(this.serializerClass, values);

    // Extract and clean CDS source
    const rawSource = (ddddlsrc?.SOURCE ?? '') as string;
    const cleanSource = stripRuntimeMetadata(rawSource);

    // Build the .asddls source file
    const sourceFilename = buildSourceFilename('DDLS', gctsObject.objectName);

    return {
      objectType: this.objectType,
      objectName: gctsObject.objectName,
      xmlContent,
      additionalFiles: [
        { filename: sourceFilename, content: cleanSource },
      ],
    };
  }

  validateGcts(gctsObject: GctsObjectData): ValidationResult {
    const errors: string[] = [];
    const warnings: string[] = [];

    if (!getFirstRow(gctsObject, 'DDDDLSRC')) {
      errors.push('Missing DDDDLSRC table (CDS source)');
    }

    return { valid: errors.length === 0, errors, warnings };
  }
}

/**
 * Strip the runtime metadata block from CDS source.
 *
 * gCTS embeds a block at the end of the source:
 *   /*+[internal] {\n"BASEINFO":\n{...}\n}* /
 *
 * This is regenerated by the target system and must not be in the portable format.
 * Also normalizes line endings from \r\n to \n.
 */
function stripRuntimeMetadata(source: string): string {
  // Normalize line endings
  let cleaned = source.replace(/\r\n/g, '\n');

  // Remove the /*+[internal] {...}*/ block
  const internalIdx = cleaned.indexOf('/*+[internal]');
  if (internalIdx >= 0) {
    cleaned = cleaned.substring(0, internalIdx).trimEnd();
  }

  return cleaned + '\n';
}
