/** Fields that are always system-specific and should be stripped */
export const COMMON_SYSTEM_FIELDS = [
  'AS4USER',
  'AS4DATE',
  'AS4TIME',
  'ACTFLAG',
  'AS4LOCAL',
  'AS4VERS',
];

/** Tables that should be entirely omitted from abapGit output (regenerated by target system) */
export const OMIT_TABLES = new Set([
  'TADIR',
  'DDTYPES',
  'TRDIR',
  'TRDIRT',
  'TMDIR',
  'ENHOBJ',
  'E070',
  'E070A',
  'E070C',
  'E071',
  'E07T',
  'SMODILOG',
  'SMODISRC',
  'PERMISSION',
]);
